apps/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path(
        'active_account/<uidb4>/<token>',
        views.active_account,
        name='active_account',
    ),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

apps/common/urls.py
from django.urls import path

from . import views

app_name = 'common'

urlpatterns = [path('', views.index, name='index')]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('auth/', include('account.urls')),
]

apps/account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True, max_length=255)
    is_active = models.BooleanField(
        _('active'),
        default=False,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self) -> str:
        return self.email


class UserNotActivated(Exception):
    pass

apps/common/models.py
from django.db import models

# Create your models here.

apps/account/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms

from .models import User


class UserChangeForm(auth_forms.UserChangeForm):
    class Meta(auth_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(auth_forms.UserCreationForm):
    class Meta(auth_forms.UserCreationForm.Meta):
        model = User
        fields = ('email',)


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ('first_name', 'email')


class AuthForm(forms.Form):
    email = forms.EmailField(
        label='Email',
        max_length=254,
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(
        label='Senha',
        max_length=254,
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

apps/account/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login as login_django
from django.contrib.auth import logout as logout_django
from django.shortcuts import redirect, render

from .decorators import not_login_required
from .facade import authenticate_user, set_active_account
from .forms import AuthForm, RegisterForm
from .models import UserNotActivated


@not_login_required()
def register(request):
    data = {'title': 'Registro'}

    if request.method == 'GET':
        form = RegisterForm()
        data['form'] = form
        return render(request, 'account/register.html', data)
    elif request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form_new = form.save(commit=False)
            form_new.is_active = False
            form_new.save()
            return redirect('account:login')
        else:
            data['form'] = form
            return render(request, 'account/register.html', data)


def active_account(request, uidb4, token):
    if set_active_account(uidb4=uidb4, token=token):
        messages.success(request, 'Seu usuário foi ativo com sucesso.')
    else:
        messages.error(request, 'A url acessada não é válida.')

    return redirect('account:login')


def logout(request):
    logout_django(request)
    return redirect('account:login')


@not_login_required()
def login(request):
    data = {'title': 'acesso'}

    if request.method == 'GET':
        form = AuthForm()
        data['form'] = form

        return render(request, 'account/login.html', data)
    elif request.method == 'POST':
        form = AuthForm(request.POST)

        if form.is_valid():
            try:
                user = authenticate_user(**form.cleaned_data)
                login_django(request, user)
                return redirect('common:index')
            except UserNotActivated:
                data['form'] = form
                messages.error(request, 'Conta não ativa.')

                return render(request, 'account/login.html', data)
            except get_user_model().DoesNotExist:
                data['form'] = form
                messages.error(request, 'Dados inválidos')

                return render(request, 'account/login.html', data)
        else:
            data['form'] = form

            return render(request, 'account/login.html', data)

apps/common/views.py
from django.shortcuts import render


def index(request):
    data = {'title': 'home'}
    return render(request, 'common/index.html', data)

apps/common/templates/common/index.html
{% extends 'base_templates/base.html' %}

{% block 'body' %}
<div class="container">
    <h1>Home</h1>
</div>
{% endblock 'body' %}

templates/base_templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link href="{% static 'base/css/base.css' %}" rel="stylesheet">
        {% block 'head' %}{% endblock %}
        <title>{{ title | capfirst }}{% block 'title' %}{% endblock %}</title>
    </head>
    <body>
        {% include 'base_templates/partials/_navbar.html' %}
        {% block 'body' %}{% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
</html>

templates/base_templates/partials/_messages.html
{% if messages %}
<div class="text-center mt-3 message-content">
    {% for message in messages %}
        <section class="alert {{message.tags}}">
            {{message}}
        </section>
    {% endfor %}
</div>
{% endif %}

templates/base_templates/partials/_navbar.html
<nav class="nav">
    <a class="nav-logo" href="{% url 'common:index' %}">Logo</a>
    <div class="nav-menu">
        <ul class="nav-list">
            <li>
                <a href="{% url 'common:index' %}">Início</a>
            </li>
        </ul>
        {% if not user.is_authenticated %}
        <ul class="nav-list">
            <li>
                <a href="{% url 'account:login' %}">Login</a>
            </li>
            <li>
                <a href="{% url 'account:register' %}">Cadastro</a>
            </li>
        </ul>
        {% else %}
        <ul class="nav-list">
            <li>
                <a href="{% url 'account:logout' %}">Logout</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>